### ISSUE TITLE
HLA*ASM

### ISSUE THREAD

**Issue by bsb2014** [DiltheyLab/HLA-LA#101]
I am wondering if you have a plan to update HLA*ASM. Is it possible to replace nucmer with minimap2 for alignment? Thanks!

**Comment by AlexanderDilthey** [comment]
Hi @bsb2014, we have no immediate plans to update HLA*ASM.

However, note that the script already supports minimap2 alignment - activated via parameter `use_minimap2 `, activated e.g. like so: `--use_minimap2  1`.
