### ISSUE TITLE
Have found no compatible reference specifications

### ISSUE THREAD

**Issue by anoronh4** [DiltheyLab/HLA-LA#123]
I have the following error: `Have found no compatible reference specifications in /juno/cmo/ccs/noronhaa/hla_dev/run_all/work/8b/8669617784455a851a1e0b162175ce/./PRG_MHC_GRCh38_withIMGT/knownReferences - create a file for this BAM file and try again. at /opt/conda/envs/hlala/bin/HLA-LA.pl line 364.`

Here are my [idxstats.txt](https://github.com/user-attachments/files/18001712/idxstats.txt)

How can i create a compatible reference for my bam?

**Comment by AlexanderDilthey** [comment]
Hi @anoronh4,

I have added a corresponding reference file - if you do a "git pull" in your HLA*LA repository, you should get the most recent files from GitHub and your BAM should process.

Please let me know in case there are any issues!

Best wishes

Alex
