### ISSUE TITLE
Only predict class I MHC alleles

### ISSUE THREAD

**Issue by Yiming-Shen** [DiltheyLab/HLA-LA#18]
Hi,

I am wondering if adding an option of specifying only class I or II alleles to predict at a time will reduce time/resource usage. If it does, I can perform HLA-PRG-LA on a resource-tensive machine with only 32GB memory. 

Thanks.

**Comment by AlexanderDilthey** [comment]
Hi @Yiming-Shen, restricting the output to only class I or class II would not significantly alter performance, as the reads are always aligned to the complete MHC graph.
