### ISSUE TITLE
I cannot index the graph

### ISSUE THREAD

**Issue by boris-milicevic** [DiltheyLab/HLA-LA#20]
So I am trying to set up HLA-LA to work on a ubuntu 18.04 docker machine. I have followed you guide and managed to receive a message "HLA*LA binary functional!".
Now I've downloaded the graph and tried to index it but it always fails at the same point. I though it could be memory related problem so I've pushed memory limit of my image to 64G but it still fails at the same spot. Now please note that I have ignored the "Modifying paths.ini" step until now, but I don't see any connection between these two steps.
Can you think of the reason why my indexing fails? 
Thank you!
![image](https://user-images.githubusercontent.com/49400822/56794833-59172d00-680f-11e9-9090-cc0e45496e39.png)

**Comment by AlexanderDilthey** [comment]
Hi,
64G should be more than enough for the indexing step. Have you tried indexing the graph outside the Docker environment, if this is possible on your infrastructure? Generally, the indexing step is only run once; depending on your infrastructure it can make sense to index it, tar it up, and then acquire and untar the archive every time you spin up up a new instance. The „killed“ in any case indicates it is not failing from an internal error; perhaps running in gdb would give a more informative message.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boris-milicevic** [comment]
I've tried coping the built binary to my host os but it cannot be easily ran on mac-OS. I will look into more memory options docker provides, maybe some of them will solve my problem.

**Comment by AlexanderDilthey** [comment]
Yes, I can imagine copying the binary would not work. You should be able, though, to build HLA*LA under MacOS if you have the gcc toolchain available.

________________________________
Von: boris-milicevic <notifications@github.com>
Gesendet: Samstag, 27. April 2019 11:24
An: DiltheyLab/HLA-LA
Cc: Alexander Dilthey; Comment
Betreff: Re: [DiltheyLab/HLA-LA] I cannot index the graph (#20)


I've tried coping the built binary to my host os but it cannot be easily ran on mac-OS. I will look into more memory options docker provides, maybe some of them will solve my problem.
