### ISSUE TITLE
No compatible reference

### ISSUE THREAD

**Issue by sethsh7** [DiltheyLab/HLA-LA#24]
Hello

I'm having issues with "no compatible reference" as I think the reference my CRAM files are aligned to is slightly non standard. I wonder if you could generate an additional known reference file from my samtools index?

Many thanks
Seth
[idxstats.txt](https://github.com/DiltheyLab/HLA-LA/files/3426988/idxstats.txt)

**Comment by AlexanderDilthey** [comment]
Hi Seth,

Yes, that's right. Yes, we can generate such a file for you! Does your reference genome include any MHC alternative contigs?

Best,

Alex
