### ISSUE TITLE
A problem when test pacbio data

### ISSUE THREAD

**Issue by Huangpq2019** [DiltheyLab/HLA-LA#25]
When I use pacbio data to test the typing effect of HLA-LA, I can't get the correct answer. 
I first searched on https://www.ebi.ac.uk using the registration number PRJNA323611, then selected the Experiment accession which is SRX1837275 to download the data, and the five data files obtained are integrated using the cat command:
![image](https://user-images.githubusercontent.com/52695850/62136350-8562ae00-b316-11e9-88da-5370543d0a34.png)
I receive the file "pacbio_test.fastq.gz".
Then I use the command "bwa mem -t 7 -M -x pacbio /mnt/data/data/ref/GRCh38_full_analysis_set_plus_decoy_hla.fa pacbio_test.fastq.gz |samtools view -bS | samtools sort -o pacbio_test_sort.bam -" to process the data and get the sorted bam file. And I index the bam file.
Next, I use the command "./HLA-LA.pl --BAM /mnt/data/data/pacbio/pacbio_test_sort.bam --graph PRG_MHC_GRCh38_withIMGT --sampleID pacbio_test --maxThreads 7 --longReads pacbio --samtools_T /mnt/data/data/NA12878_final/GRCh38_full_analysis_set_plus_decoy_hla.fa" to run the HLA-LA, I can only get the result like this:
![image](https://user-images.githubusercontent.com/52695850/62136471-c35fd200-b316-11e9-9343-3e50c2935f7c.png)
The file "hla" is empty. 
I can't get the right typing result. Would you be so kind and help me to solve this problem? The log of command execution is attached to the attached file.

**Comment by AlexanderDilthey** [comment]
@AlexanderDilthey Followed up via email.
