### ISSUE TITLE
Sample names with strange characters

### ISSUE THREAD

**Issue by hcurley2** [DiltheyLab/HLA-LA#28]
Hi 

I am using HLA-LA within the 1,000 genomes project environment and unfortunately sample names within the BAMs are for example LP000000-DNA_A01 and so your program gives an error. I can reheader using samtools to LP00000DNAA01 and then the program works fine (but in order to do this I have to copy the bam into a writeable file by me first...). As I am trying to run this on thousands of bams, this is becoming very time consuming and memory gobbling! Is there anything I can do to modify the code to allow - and/or _ into sample names? 

Any help would be very appreciated!

Helen

**Comment by AlexanderDilthey** [comment]
Hi Helen,

Not sure whether this is what you need, but you can specify arbitrary sample names via the `--sampleID` parameter (i.e. you could do `--BAM LP000000-DNA_A01.bam and --sampleID LP00000DNAA01 `. Would this solve your problem?

Best,

Alex
