### ISSUE TITLE
Improvements to Documentation

### ISSUE THREAD

**Issue by DarioS** [DiltheyLab/HLA-LA#29]
In the section titled Basics is a link to a blog post which no longer exists. IMGT is regularly updated. The overview should specify the version of the database used to create the data package (e.g. 3.34.0) to enhance research results reproducibility and identifability. The reference is to the pre-print, but it should instead be to the journal article in _Bioinformatics_.

**Comment by lenapfitzer** [comment]
The files in the data package are dated to 15th of March 2017. This probably means that IPD-IMGT/HLA Release 3.27.0 (01/2017) was used.

**Comment by AlexanderDilthey** [comment]
@DarioS Thanks for highlighting these issues, we've now fixed the links!
@lenapfitzer We're still on 3.21.0. We plan on releasing a new graph in 2020, when we also add support for somatic variant calling.

**Comment by Stikus** [comment]
@AlexanderDilthey 2020 year ending in two months - any news about new graph?
