### ISSUE TITLE
bamtools installation problem 

### ISSUE THREAD

**Issue by cjieming2** [DiltheyLab/HLA-LA#31]
Hi I got an error in the mapper/processBAM.cpp:4341 while I was compiling. This is an older version of bamtools, so I did follow the instructions to comment in the include statement that was previously commented out. But the error still persists... Any help is appreciated! Thank you!

~/software/HLA-LA/src/mapper/processBAM.cpp:4341: undefined reference to `BamTools::BamReader::GetReferenceID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../obj/processBAM.o: In function `mapper::processBAM::updateBAMSelectors()':

**Comment by AlexanderDilthey** [comment]
Hi @cjieming2, which version of bamtools are you using, and is this the only error? Could you post the full commands generated by make and all output?

**Comment by cjieming2** [comment]
My bamtools version:
$> bamtools --version
bamtools 2.4.1

I simply ran the following command
$> make all

I attach the output to the command - it's too long to post.

Thanks for the help!
[install.log](https://github.com/DiltheyLab/HLA-LA/files/3881964/install.log)

**Comment by AlexanderDilthey** [comment]
Hmm, this is weird. The g++ commands look OK to me. Did you use the same version of g++ to build bamtools / boost and HLA*LA?
