### ISSUE TITLE
if I have fastq paired read data, what should i do?

### ISSUE THREAD

**Issue by PavitaKae** [DiltheyLab/HLA-LA#33]
I noticed that your code extract bam to fastq first, and mapping with your reference. 
if I have fastq already, Should i skip extract bam file and use my fastq as input to your program? How?

**Comment by AlexanderDilthey** [comment]
There is an un-tested code branch in the C++ component of HLA*LA that accepts FASTQ files as input, but we currently don't support this option. In any case there are not going to be any great performance advantages, as, even if FASTQ is supplied, the first step will always consist of a complete mapping of all reads.
