### ISSUE TITLE
User-defined path to graph directory

### ISSUE THREAD

**Issue by jafors** [DiltheyLab/HLA-LA#35]
Hi @AlexanderDilthey,
first of all, thanks for your work, HLA-LA works like a charm, but still there is one thing I'd like to suggest:
I use HLA-LA in various projects and have integrated it in a pipeline mostly based on snakemake and conda. So, whenever I use the pipeline on a new analysis, the conda environments are re-built in the specific project folder. Since HLA-LA fixes the directory of the PRGs to the specific location of installation, I would need to download and index the graph for every project even if I wanted to use the same reference in all of them.

I think that the ability of a user-defined graph directory which allows to use already downloaded and indexed graphs would increase the reusability in this scenario and might be a helpful feature for some users.

I already worked a bit on a possible solution, so if you think this could be a helpful addition to HLA-LA, I would be happy to discuss it more deeply and make a PR.

Thanks in advance!
Best,
Jan

**Comment by AlexanderDilthey** [comment]
Hi @jafors,

I think this would be a great feature! Yes, let's discuss and it would be great if you could submit a PR!

Best,

Alex

**Comment by jafors** [comment]
Hi @AlexanderDilthey ,

thanks for the merge! Are you planning to do a new release soon? Would be great to incorporate this change in the conda version soon.

**Comment by AlexanderDilthey** [comment]
Hi @jafors,

Yes, it would be great to update the conda version! We're also planning to extend the HLA typing functionality to the non-PBR exons/introns and to somatic variant calling - not sure whether we should wait until this is implemented, or push the current version. Any thoughts?

**Comment by jafors** [comment]
That sounds great, looking forward to this!
For now, I'd personally appreciate a new release rather soon, because we want to incorporate the HLA typing into a more shareable pipeline, which will definitely benefit from this feature.

**Comment by jafors** [comment]
Hi @AlexanderDilthey,
any new insights if you want to do a new release before your upcoming changes?

Best,
Jan

**Comment by lkuchenb** [comment]
@jafors https://github.com/lkuchenb/MultiHLA - I went for a not so pretty workaround. Would be really great to see this fixed.

**Comment by jafors** [comment]
@lkuchenb Yeah, I see. I found a solution for my workflow as well, tried to avoid this `CONDA_PREFIX` stuff. FYI, I also did a PR (#50) to make the graph preparation more accessible.

Nice work, btw. If you have time to chat someday, I'd gladly reach out. :)

**Comment by chrlundtoft** [comment]
@AlexanderDilthey: Thanks for a great tool!
Any news on a update of HLA-LA and release of a new graph mentioned in #29 ? I'm planning an analysis of a large number of samples, but would probably wait if an update is around the corner.
