### ISSUE TITLE
Graph path for Conda install

### ISSUE THREAD

**Issue by NTNguyen13** [DiltheyLab/HLA-LA#39]
Hi, I have tried HLA:LA recently, I installed it through bioconda, however, I haven't seen any instruction at the end of the installation. 

I downloaded the `PRG_MHC_GRCh38_withIMGT` graph manually, unzip them into the path `~/anaconda3/opt/hla-la/src/graphs/` (the full path is `~/anaconda3/opt/hla-la/src/graphs/PRG_MHC_GRCh38_withIMGT`). However, when I run the command, it still gives error:
```

HLA-LA.pl --BAM $file --sampleID $sample_name --graph PRG_MHC_GRCh38_withIMGT/ --maxThreads 10 --workingDir ~/test_hlala
HLA-LA.pl

Identified paths:
        samtools_bin: ~/anaconda3/bin/samtools
        bwa_bin: ~/anaconda3/bin/bwa
        java_bin: ~/anaconda3/bin/java
        picard_sam2fastq_bin: ~/anaconda3/bin/picard
        General working directory: ~/test_hlala
        Sample-specific working directory: ~test_hlala/0411_01_01

Graph directory ~/opt/hla-la/src/../graphs/PRG_MHC_GRCh38_withIMGT/ not found - valid graph names are subdirectories of the graphs directory in the HLA-LA root at ~/anaconda3/bin/HLA-LA.pl line 198.
```

I checked the directory:
```

file "/home/nguyen/anaconda3/opt/hla-la/src/Graph/PRG_MHC_GRCh38_withIMGT/"
/home/nguyen/anaconda3/opt/hla-la/src/Graph/PRG_MHC_GRCh38_withIMGT/: directory

```

and the files inside
```
ls
extendedReferenceGenome  knownReferences  mapping  mapping_PRGonly  PRG  referenceGenomeSimulations  sampledReferenceGenomes  sequences.txt  translation

```

What did go wrong in my case?

**Comment by davetang** [comment]
The error seems to indicate that `HLA-LA.pl` is looking for the directory at `~/opt/hla-la/src/../graphs/PRG_MHC_GRCh38_withIMGT/`, which equals `~/opt/hla-la/graphs/PRG_MHC_GRCh38_withIMGT/`

However, the directory exists at `~/anaconda3/opt/hla-la/src/Graph/PRG_MHC_GRCh38_withIMGT/`.

**Comment by tinyheero** [comment]
I ran into the same problem. The graph data needs to be downloaded and placed in a folder `graphs` folder that exists in the same level as the `src` and `bin` folder. So in your case, it should be placed at `~/anaconda3/opt/hla-la/graphs/PRG_MHC_GRCh38_withIMGT`.

**Comment by NTNguyen13** [comment]
Hi, moving the graph to `opt/hla-la` is correct, thank you both!

**Comment by mschubert** [comment]
Also note https://github.com/DiltheyLab/HLA-LA/issues/96:

> `HLA-LA.pl` has the (undocumented) `customGraphDir` command line parameter - it seems that this is what you may need?
