### ISSUE TITLE
Installing HLA*LA with bug

### ISSUE THREAD

**Issue by masen0407** [DiltheyLab/HLA-LA#41]
/usr/bin/ld: BFD version 2.20.51.0.2-5.42.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
make: *** [makefile:109: HLA-LA] Error 1

**Comment by AlexanderDilthey** [comment]
Hi @masen0407, it seems that this is a bug in the ld program - perhaps try updating your operating system or compiler tools? As this doesn't seem to be an error in HLA-LA, I'll close this issue.
