### ISSUE TITLE
Typing of HLA-DP Locus

### ISSUE THREAD

**Issue by tinyheero** [DiltheyLab/HLA-LA#43]
Hi there,

Thanks for this tool. Is it possible to use HLA*LA to type the HLA-DP locus? When I was reading the paper (https://academic.oup.com/bioinformatics/article/35/21/4394/5426702), I didn't see any mention of the HLA-DP locus in any of the results/benchmarking.

Kind regards,

Fong

**Comment by AlexanderDilthey** [comment]
Hi Fong,

Yes - by default you get genotypes for the following HLA loci:

A
B
C
DQA1
DQB1
DRB1
DPA1
DPB1
DRA
DRB3
DRB4
E
F
G
H
K
V

Best,

Alex

________________________________
Von: Fong Chun Chan <notifications@github.com>
Gesendet: Mittwoch, 22. Juli 2020 14:05
An: DiltheyLab/HLA-LA <HLA-LA@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [DiltheyLab/HLA-LA] Typing of HLA-DP Locus (#43)


Hi there,

Thanks for this tool. Is it possible to use HLA*LA to type the HLA-DP locus? When I was reading the paper (https://academic.oup.com/bioinformatics/article/35/21/4394/5426702), I didn't see any mention of the HLA-DP locus in any of the results/benchmarking.

Kind regards,

Fong
