### ISSUE TITLE
Allowing for non-alphanumeric characters in sample IDs

### ISSUE THREAD

**Issue by tinyheero** [DiltheyLab/HLA-LA#45]
Hi there,

Is it possible to allow for the `--sampleID` argument to accept non-alphanumeric characters? I often work with identifiers that contain a `-` in it and when I try to run for example something like this:

```
HLA-LA.pl \
        --BAM tumour-sample.bam \
        --graph PRG_MHC_GRCh38_withIMGT \
        --sampleID tumour-sample \
        --maxThreads 1 \
        --workingDir output/hla_la
```

I get this error:

```
Please use only alphanumeric characters - \w+ - for --sampleID at /projects/ace_benchmarking/miniconda3/envs/hla-la/bin/HLA-LA.pl line 147.
```

I could specify a `--sampleID` devoid of any non-alphanumeric characters, but this adds post-processing step to marry the results with the original sample identifiers, which I would like to avoid.

Kind regards,

Fong

**Comment by AlexanderDilthey** [comment]
Hi @tinyheero,

This is now fixed (`-` and `_` are allowed).

Best wishes

Alex
