### ISSUE TITLE
error when extracting unmapped reads

### ISSUE THREAD

**Issue by wt2015-github** [DiltheyLab/HLA-LA#58]
The following code could get an error of bam header when there is no unmapped reads

my $extraction_command_unmapped = qq($samtools_bin view $BAM '*' | awk '{if (\$3 == "*") print \$0}' | $samtools_bin view -bo $target_extraction_unmapped -);

how about this:

my $extraction_command_unmapped = qq($samtools_bin view -bo $target_extraction_unmapped $BAM '*');
or
my $extraction_command_unmapped = qq($samtools_bin view -f4 -bo $target_extraction_unmapped $BAM);
but the second one could be a problem when only one of the paired-end reads mapped

**Comment by AlexanderDilthey** [comment]
Hey @wt2015-github,

Thank you! This is now fixed! (https://github.com/DiltheyLab/HLA-LA/commit/c532e1e4805f6a1b5d0496449329b08dc6611f97)

Best wishes

Alex
