### ISSUE TITLE
extraction file for custom reference

### ISSUE THREAD

**Issue by raval91** [DiltheyLab/HLA-LA#60]
Hello!

I have been trying to run HLA-LA but receive the following error 

`Have found no compatible reference specifications in /home/hisd/HLA-LA/src/../graphs/PRG_MHC_GRCh38_withIMGT/knownReferences - create a file for this BAM file and try again. at /home/hisd/HLA-LA/src/HLA-LA.pl line 364.`

I have tried to create an extraction file based on the reference I used to align, and the output of idxstats... please see attached, the output of idxstats, and the extraction file I then created from it. Have I done something wrong when making the extraction file? 

The extraction file was placed in both the graphs/PRG_MHC_GRCh38_withIMGT/knownReferences and src/additionalReferences/PRG_MHC_GRCh38_withIMGT/ directories. 

[GRCh38_latest_genomic.txt](https://github.com/DiltheyLab/HLA-LA/files/6685202/GRCh38_latest_genomic.txt)
[barcode01_idxstats.txt](https://github.com/DiltheyLab/HLA-LA/files/6685210/barcode01_idxstats.txt)

Thank you for your help!
Rohan.

**Comment by AlexanderDilthey** [comment]
Hi @raval91,

I think there are two issues:
- your idstats and the extraction file are not in sync - the extraction file should have 1 line for each line in idxstats, and this is not the case
- I think your extraction file misses some alternative MHC contigs, e.g. NT_187692.1, NT_167244.2 etc. - for these, you should set `ExtractCompleteContig`to 1. Compare with this file here, which also has alternative MHC contigs: https://github.com/DiltheyLab/HLA-LA/blob/master/additionalReferences/PRG_MHC_GRCh38_withIMGT/Additional_B38_3.txt

Best wishes

Alex
