### ISSUE TITLE
Is it possible to declare multiple CRAM files?

### ISSUE THREAD

**Issue by kantale** [DiltheyLab/HLA-LA#66]
Hi,

I am trying to process EGAF CRAM Files from EGA. A single sample might contain multiple CRAM files (8) and each file is ~4GB. Do I have to merge these files in a single CRAM, or is it  possible to declare multiple CRAM files in a single run?

**Comment by AlexanderDilthey** [comment]
Hi @kantale,

You have to merge them beforehand.

Best,

Alex
