### ISSUE TITLE
error for HLA-ASM

### ISSUE THREAD

**Issue by hmyh1202** [DiltheyLab/HLA-LA#70]
Hi:

I have download now version  reference_HLA_ASM//exonAlignments  and run HLA-ASM， and  got :

Died at HLA-ASM.pl line 1480, <ALIGNMENT> line 35531. 

sound like some format error .

**Comment by hmyh1202** [comment]
Finally I use your  shared  reference_HLA_ASM//exonAlignments file, and can be continued,  but it was reported that: 
Truncate allele sequence for C*04:09N at  HLA-ASM.pl line 1542  for several times.

**Comment by AlexanderDilthey** [comment]
This is fine, just a warning.
