### ISSUE TITLE
Unknown option: action when HLA-LA install by conda

### ISSUE THREAD

**Issue by rosaricla** [DiltheyLab/HLA-LA#71]
Good morning,

I've installed HLA-LA using bioconda (`conda install hla-la`)  and I've downloaded the data package. However, when I tried to index the graph using the command that you provide:

`HLA-LA.pl --action prepareGraph --PRG_graph_dir ../graphs/PRG_MHC_GRCh38_withIMGT`

I get the following error:

```
Unknown option: action
Unknown option: prg_graph_dir
```

**Comment by ShawnSimp** [comment]
Was this issue ever solved? I'm getting the same issue. Is indexing the graph still necessary with the conda installation?

**Comment by rosaricla** [comment]
@ShawnSimp I finally didn't index the graph and the tool worked correctly so I think it is not necessary to indexing with the conda installation.

**Comment by ShawnSimp** [comment]
Actually you need to locate your hla installation in conda  within ..hla-la/bin/  you will find the HLA-LA run file that you have to use for the indexing of the graph.
