### ISSUE TITLE
v1.0.2 no conda available

### ISSUE THREAD

**Issue by manolis2023** [DiltheyLab/HLA-LA#74]
Hi, I foundunder conda only the v1.0.1 . Do you have a link for the v1.0.2 or could you add it?
Best

**Comment by dlaehnemann** [comment]
I'm trying to get the conda recipe to work with this newer version, there's a pull request tracking the work here:
https://github.com/bioconda/bioconda-recipes/pull/35254

However, it seems like the setup with different dependencies is quite complex, so this might take a while. Also, as of now, this will skip version 1.0.2 and instead go for version 1.0.3 directly.

**Comment by dlaehnemann** [comment]
The latest update to that pull request passes tests, and I have started the upload process. So version `1.0.3` should be available via bioconda within the next hours.

The recipes does some basic testing. However, I cannot guarantee that everything will work, as the dependencies are quite complex and I am not expert when it comes to Perl and conda. Thus, feel free to report anything that doesn't work -- probably best to report this on bioconda, and maybe pinging in @AlexanderDilthey over there, so he can chime in with ideas for fixes.

**Comment by AlexanderDilthey** [comment]
Thank you @dlaehnemann! Did everything work out in the end?

**Comment by dlaehnemann** [comment]
I think so, `v1.0.3` was merged over there. So feel free to close this issue over here.

**Comment by AlexanderDilthey** [comment]
Thank you @dlaehnemann!
