### ISSUE TITLE
HLA-LA graph for KIR regions

### ISSUE THREAD

**Issue by dagkesamanskaya** [DiltheyLab/HLA-LA#76]
Dear DiltheyLab team,

I have found your tool for human leukocyte antigen regions inference and I am extremely interested in trying it for KIR regions.

It is shown in github that you also tried to generate the PRG for its regions (https://github.com/DiltheyLab/HLA-LA/blob/master/Update%20KIR%20data.txt). May I ask you to help me to generate it too?

There is a good instruction provided, but the paths are unfortunately relative.

Thank your for your efforts in this area and for your answer in advance

**Comment by AlexanderDilthey** [comment]
Hi @dagkesamanskaya,

KIR inference is currently not supported unfortunately (and the model of HLA*LA does not work very well for KIR genes).

Best wishes,

Alex
