### ISSUE TITLE
Error: Have found no compatible reference specifications

### ISSUE THREAD

**Issue by Sahu-Mousumi** [DiltheyLab/HLA-LA#79]
Hi!
I am trying to use HLA-LA for HLA typing but ending up generating error as below. I am also attaching output of the samtools idxstats of my bam file.

I was wondering if anyone can help me resolving this!

Error:

Identified paths:

       samtools_bin: /usr/local/apps/samtools/1.9/bin/samtools
       bwa_bin: /usr/local/apps/bwa/0.7.17/bwa
       java_bin: /usr/bin/java
      picard_sam2fastq_bin: /usr/local/apps/picard/2.9.2/build/libs/picard.jar
      General working directory: /gpfs/gsfs11/users/Gourh_Lab/hla-la
      Sample-specific working directory: /gpfs/gsfs11/users/Gourh_Lab/hla-la/bqsrS10

Have found no compatible reference specifications in /usr/local/apps/HLA-LA/1.0.1/src/../graphs/PRG_MHC_GRCh38_withIMGT/knownReferences - create a file for this BAM file and try again. at /usr/local/apps/HLA-LA/1.0.1/src/HLA-LA.pl line 309.

Thanks!

[reference_extraction.txt](https://github.com/DiltheyLab/HLA-LA/files/9253894/reference_extraction.txt)

**Comment by AlexanderDilthey** [comment]
Solved after email exchange.
