### ISSUE TITLE
Version of picard

### ISSUE THREAD

**Issue by serge2016** [DiltheyLab/HLA-LA#8]
There is one more problem:
https://github.com/broadinstitute/picard/releases/tag/2.9.4
Picard now has one single jar-file! And I can't provide a path to `picard_sam2fastq_bin`:
```
root@5f5e7a4b6c25:/outputs/soft/HLA-PRG-LA# ./src/HLA-PRG-LA.pl --picard_sam2fastq_bin "/soft/picard/picard-2.9.0-all.jar SamToFastq"
Command-line supplied value/file for parameter picard_sam2fastq_bin not existing at ./src/HLA-PRG-LA.pl line 368.
```

The last version of picard with separate JAR-files is picard-tools is 1.123:
https://github.com/broadinstitute/picard/releases/tag/1.123

**Comment by serge2016** [comment]
```
root@5f5e7a4b6c25:/outputs/soft/HLA-PRG-LA# ./src/HLA-PRG-LA.pl --bwa_bin $BWA --samtools_bin /soft/samtools/bin/samtools --picard_sam2fastq_bin /soft/picard-tools-1.119/SamToFastq.jar --BAM /outputs/NA12878.cram --graph ../graphs/PRG_MHC_GRCh38_withIMGT --sampleID NA12878_serge --maxThreads 8 --workingDir ./
```
This works.

**Comment by AlexanderDilthey** [comment]
As an interim solution, you can edit line 319 of HLA-PRG-LA.pl, which should currently be:

elsif($picard_sam2fastq_bin =~ /picard-tools$/)

and replace it with

elsif(1)

Then the following should work:

./src/HLA-PRG-LA.pl --picard_sam2fastq_bin "/soft/picard/picard-2.9.0-all.jar"

**Comment by holtjma** [comment]
Following the above suggestion, I had to change lines 350-353 to the following to get it past this step using Picard v2.18.7:
```
elsif(1)
{
	$FASTQ_extraction_command = qq($java_bin -Xmx10g -XX:-UseGCOverheadLimit -jar $picard_sam2fastq_bin SamToFastq VALIDATION_STRINGENCY=LENIENT I=$target_extraction F=$target_FASTQ_1 F2=$target_FASTQ_2 FU=$target_FASTQ_U 2>&1);
}
```

**Comment by nyzhoulang** [comment]
I provide a path to picard_sam2fastq: `picard_sam2fastq_bin: /home/tingze/miniconda2/bin/picard`.
And the error is:`'SamtoFastq' is not a valid command. See PicardCommandLine -h for more information.
Did you mean this?
        SamToFastq`
So I replace `
        $FASTQ_extraction_command = qq($picard_sam2fastq_bin SamtoFastq `
with`$FASTQ_extraction_command = qq($picard_sam2fastq_bin SamToFastq `
 in line 380 of `HLA-LA.pl`
This works.
My HLA-LA installed via bioconda. And using picard-tools-1.92-0.

**Comment by AlexanderDilthey** [comment]
Thank you! I've integrated your fix!
