### ISSUE TITLE
Inconsistent need for hla_nom_g.txt?

### ISSUE THREAD

**Issue by jfass** [DiltheyLab/HLA-LA#81]
I'm using HLA*LA 1.0.1 installed in a conda environment. Out of quite a few samples analyzed, both whole exome and RNA-Seq, I'm seeing two samples that fail, and in at least one of those cases, it quits after not being able to find hla_nom_g.txt in the conda src folder. I'm testing again after adding to the path, but why the inconsistent need?

**Comment by AlexanderDilthey** [comment]
Hi @jfass,

The file is always required. I do not know what causes the behaviour you observed.

Best
-Alex
