### ISSUE TITLE
Error with test data

### ISSUE THREAD

**Issue by mirpedrol** [DiltheyLab/HLA-LA#85]
Hello,

We are trying to use HLA-LA, starting with the provided test data, and we find an error indicating that the data is not correct.

We downloaded the provided .tar.gz and checked that the md5sum was correct. Unzip the file and try to build a graph with the following command:
`/<PATH>/hla-la/bin/HLA-LA --action prepareGraph --PRG_graph_dir graphs/PRG_MHC_GRCh38_withIMGT`

And we get the following error:
```
Read graph from graphs/PRG_MHC_GRCh38_withIMGT
86600000terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot read CODE from line, expect 3 fields, got2! Line: 7974777_after_HLA-DPB1_935315|||*x||51
Aborted (core dumped)
```

We tried to manually fix the syntactic errors in the file and rerun the command, but then a different error appeared:
```
6600000/30207166[E]terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_lexical_cast>'
  what():  bad lexical cast: source type value could not be interpreted as target
Aborted (core dumped)
```

Do you have any idea of what would be the problem? Any help will be appreciated. Thank you!

**Comment by AlexanderDilthey** [comment]
I am not sure I can reproduce this issue - can you check that the line as reported by the error message is really present in the file PRG_MHC_GRCh38_withIMGT/PRG/graph.txt?

I just downloaded the .tar.gz file, did a fresh extraction, and the line I get in there is:

`7974777_after_HLA-DPB1_935315|||*|||51`

**Comment by mirpedrol** [comment]
That's weird, now trying again (using the same file, not downloading it fresh), there's a different error. Also, the line that we find with a grep is the correct one that you copied. 

```
 [ Wed Jan 11 16:12:18 2023 ] Read graph from graphs/PRG_MHC_GRCh38_withIMGT
400000/30207167[E]HLA-LA: Graph/Graph.cpp:2518: void Graph::readFromFile(std::string): Assertion `emissionString.length() == 1' failed.
Aborted (core dumped)
```

**Comment by AlexanderDilthey** [comment]
Hmm, is it possible we are dealing with file corruption / hardware issues here?

**Comment by AlexanderDilthey** [comment]
Hi @mirpedrol, I assume running on a different machine solved the problem? I will close this now, but feel free to re-open if not!

Alex

**Comment by mirpedrol** [comment]
Yes! I could run the tool now, thank you for your help!
