### ISSUE TITLE
error after only use chr6 mapping

### ISSUE THREAD

**Issue by ksmpooh** [DiltheyLab/HLA-LA#88]
Hello

I tried to use HLA region targeted sequencing and only chr6 mapped bam file (both hg19 and GRch38), and running HLA*LA

error massage like this :
`Have found no compatible reference specifications in /usr/local/bin/HLA-LA/src/../graphs/PRG_MHC_GRCh38_withIMGT/knownReferences - create a file for this BAM file and try again. at /usr/local/bin/HLA-LA/src/HLA-LA.pl line 309.`

Before this, it was mapped by whole reference genome (hg19), it worked well.
But I just extracted chr6 from reference fasta, and mapped , it did not work.

Anyone knows these problems, please help me~ 

Thanks~

**Comment by AlexanderDilthey** [comment]
Hi @ksmpooh,

It seems that this is basically the same issue as here: https://github.com/DiltheyLab/HLA-LA/issues/89 - and the solution would be identical, i.e. you can create a reference specification file for your reduced reference genome, and everything should work fine. Let me know if you require assistance.

Best wishes

Alex
