### ISSUE TITLE
Please use only alphanumeric characters for --sampleID

### ISSUE THREAD

**Issue by serge2016** [DiltheyLab/HLA-LA#93]
Hello, dear author!

Is this check really necessary:
https://github.com/DiltheyLab/HLA-LA/blob/fb8ae1cde7783d6cf441a80319e943f63f3b6276/HLA-LA.pl#L186

I hope `-` sign in the sampleID should not be a problem...

**Comment by AlexanderDilthey** [comment]
Hi @serge2016,

Thank you for the suggestion. HLA*LA now allows for dashes in sample IDs.

Best,

Alex

**Comment by serge2016** [comment]
Thank you!

**Comment by AlexanderDilthey** [comment]
@serge2016 Underscore characters (`_`) now also allowed!
