### ISSUE TITLE
Error with graphs directory

### ISSUE THREAD

**Issue by shawez** [DiltheyLab/HLA-LA#94]
Hello,

I recently started using HLA-LA which is installed on the cluster of my institute. 

I also downloaded an additional data package as per the instructions from the developers. Then I run the following line of code to index the graph locally. 

/services/tools/hla-la/1.0.3/opt/hla-la/bin/HLA-LA --action prepareGraph --PRG_graph_dir /home/shawez/HLA-LA/graphs/PRG_MHC_GRCh38_withIMGT

Now, I am trying to run HLA-LA on my one sample using a BAM file.

# My code is

cd /services/tools/hla-la/1.0.3/bin
./HLA-LA.pl --BAM /home/shawez/HLA-LA/rawData/sample1.recal.bam --graph PRG_MHC_GRCh38_withIMGT --sampleID sample1 --workingDir /home/shawez/HLA-LA/outPut

I am getting the following error:

Graph directory /services/tools/hla-la/1.0.3/opt/hla-la/src/../graphs/home/shawez/HLA LA/graphs/PRG_MHC_GRCh38_withIMGT not found - valid graph names are subdirectories of the graphs directory in the HLA-LA root at ./HLA-LA.pl line 247.

I tried to change the path of the graph but did not work.

Is there any other possible solution you can suggest for this issue?

Thank you very much.

Best,

Shawez

**Comment by AlexanderDilthey** [comment]
Hi @shawez,

You can add the parameter `customGraphDir` to specify a custom graph files search directory.

You still specify `--graph`, i.e. your full call may e.g. look like this: `./HLA-LA.pl --BAM /home/shawez/HLA-LA/rawData/sample1.recal.bam --graph PRG_MHC_GRCh38_withIMGT --customGraphDir /path/to/graph/dir --sampleID sample1 --workingDir /home/shawez/HLA-LA/outPut`

When using this command, HLA*LA will expect to find the graph files in `/path/to/graph/dir/PRG_MHC_GRCh38_withIMGT `.

Best wishes

Alex
