### ISSUE TITLE
No compatible reference

### ISSUE THREAD

**Issue by angyonghaseyo** [DiltheyLab/HLA-LA#98]
![image](https://github.com/DiltheyLab/HLA-LA/assets/89739997/cc3dfbe4-b425-4328-bbc4-7da7f44bac69)

@AlexanderDilthey Any ideas on how to solve this error? Please do help as I have tried to solve with many other ways, but to no avail. Like doing https://github.com/DiltheyLab/HLA-LA/issues/27 wont work for me.

[idxstats.txt](https://github.com/DiltheyLab/HLA-LA/files/12091374/idxstats.txt)
[PRG_MHC_GRCh38_withIMGT.txt](https://github.com/DiltheyLab/HLA-LA/files/12091376/PRG_MHC_GRCh38_withIMGT.txt)

**Comment by AlexanderDilthey** [comment]
Hi @angyonghaseyo,

I have added a reference specification file for your reference (https://github.com/DiltheyLab/HLA-LA/blob/master/additionalReferences/PRG_MHC_GRCh38_withIMGT/Additional_B38_3.txt) - do a fresh pull from GitHub and you should be able to process your BAM.

Best wishes

Alex

**Comment by angyonghaseyo** [comment]
Hi @AlexanderDilthey, Im still facing the same error, any advice on that?

**Comment by AlexanderDilthey** [comment]
Could you do an `ls` on the folder specified in the error message and post the results here?

**Comment by angyonghaseyo** [comment]
Hi, u mean this?
(base) angyong@comp1:~/HLA-LA/graphs/PRG_MHC_GRCh38_withIMGT/knownReferences$ ls
1000G_B37_noChr.txt  1000G_B38.txt  Additional_B38_3.txt  B37_generic_noChr.txt  PRG_MHC_GRCh38_withIMGT.txt

**Comment by AlexanderDilthey** [comment]
Yes, thank you!

Could you also send me the contents of the directory `~/HLA-LA/src/additionalReferences/PRG_MHC_GRCh38_withIMGT`?

**Comment by angyonghaseyo** [comment]
Hi, the contents of the directory are as following:

Additional_B38_2.txt  B37_generic_noChr_withHHV.txt  chm13v2.txt                        hg19.txt
Additional_B38_3.txt  B37_noChr_noGL.txt             G1000_Ymasked.txt                  Illumina_B38.txt
Additional_B38.txt    B37_withChr_M2.txt             GEL_B38.txt                        PRG_MHC_GRCh38_withIMGT.txt
B37_for_Nobuyuki.txt  B37_withChr.txt                GRCh38.p12.genome.XY_idxstats.txt  Valentin_B38.txt

**Comment by angyonghaseyo** [comment]
@AlexanderDilthey do let me know if theres any info, I suspect my idxstats file is showing contig number instead of accession number(will try to change and see if the not compatible reference specs error still pops up

**Comment by AlexanderDilthey** [comment]
OK, this sounds like a plan - let me know if this works!

**Comment by pablosoro** [comment]
Hi @AlexanderDilthey

I'm facing the same problem with
`Have found no compatible reference specifications in /nemo/stp/babs/working/barriop/.conda/envs/HLA_typing/opt/hla-la/src/../graphs/PRG_MHC_GRCh38_withIMGT/knownReferences - create a file for this BAM file and try again.  at /camp/stp/babs/working/barriop/.conda/envs/HLA_typing/bin/HLA-LA.pl line 364.`

Should I upload my `idxstats` file(s) here o create a new issue? Many thaks in advance.

Best,
Pablo

**Comment by AlexanderDilthey** [comment]
Yes @pablosoro, please do!
